### ISSUE TITLE
Soul Crush trigger

### ISSUE THREAD

**Issue by Popetato** [Caldraeus/chat-classes-error-reporting#5]
**Description:** The soulcrusher's Soul Crush triggers on all non-critical attacks, and not on critical hits at all (thus granting 400 coolness on roughly every other attack). Basically, it seems like the trigger is reversed.

**Steps to Reproduce:** As a soulcrusher, repeatedly attack the same target.

**Screenshots:**

![Soul Crush Error](https://user-images.githubusercontent.com/78700711/107157511-72408d80-6952-11eb-8866-6a96b497ff18.png)

![Soul Crush Error 2](https://user-images.githubusercontent.com/78700711/107157516-75d41480-6952-11eb-8a40-c87732541e1b.png)

**Comment by Caldraeus** [comment]
You’re right on this. Looks like it was checking for the reversed condition. Will fix this right away.
