### ISSUE TITLE
Boom Bot Explodes on User

### ISSUE THREAD

**Issue by Popetato** [Caldraeus/chat-classes-error-reporting#6]
**Description:** A Boom Bot can explode on the user who set it. I _think_ it happened because I had the Burning status effect -- when the bot replaced my text with the fiery version, the boom bot counted it as a different user sending a message, and exploded. Presumably this would also affect Shattered, Polymorphed, etc.

**Steps to Reproduce:** Release a Boom Bot, then become effected by a status effect which affects the text of your messages. While stull under this effect, be the first person to send a message after the boom bot's timer goes off.

**Screenshot:**
![Screenshot_20220201-115928_Discord](https://user-images.githubusercontent.com/78700711/152280213-c5ef524e-a27d-456d-a17f-df2fa7a2c9fd.jpg)

**Comment by Caldraeus** [comment]
Nice catch. Will check out in a moment.

**Comment by Caldraeus** [comment]
Should (?) be resolved. Comment on here again if it's not.
