### ISSUE TITLE
Status Effects Cause Message Duplication

### ISSUE THREAD

**Issue by Popetato** [Caldraeus/chat-classes-error-reporting#7]
**Descrption:** If a user has two status effects which both alter the next of their messages (such as Burning and Woohoo), the bot executes both alterations -- separately. This causes the message to be sent twice (or probably more, if they have more than two conditions), once affected by each condition.
**Steps to Replicate:** Become affected by two status effects which alter your messages, then send a message.
**Screenshot:**
![Screenshot_20220203-093829_Discord](https://user-images.githubusercontent.com/78700711/152463217-05ee2679-4551-4417-a990-32549401b658.jpg)

**Comment by Caldraeus** [comment]
Resolved. Thank you.
